version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    command: elasticsearch -E network.host=0.0.0.0 -E discovery.zen.minimum_master_nodes=1
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.2
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash-docker.conf:/etc/logstash/conf.d/logstash.conf
      - ./logs-template.json:/etc/logstash/templates/logs-template.json
    ports:
      - "5000:5000"
      - "5044:5044"
    links:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
